### ISSUE TITLE
got "public.version" does not exist error

### ISSUE THREAD

**Issue by wangxiexe** [ArekSredzki/electron-release-server#109]
Applying disable cache policy
Windows Update Search Query { platform: [ 'windows_32' ],
  version: '0.0.370',
  channel: 'stable' }
Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
error: relation "public.version" does not exist
    at Connection.parseE (/home/rd/micloudpc-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/rd/micloudpc-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/rd/micloudpc-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

Details:  error: relation "public.version" does not exist

seems the db tables are not well populated, any suggestion ? thx

**Comment by ArekSredzki** [comment]
You must run the server in dev mode on first run in order to initialize the tables

**Comment by wangxiexe** [comment]
thx, it works.
