### ISSUE TITLE
error: sails-pg-session#PostSQLStore - error: password authentication failed for user

### ISSUE THREAD

**Issue by jjprestes** [ArekSredzki/electron-release-server#138]
I'm getting this error when try to access a remote postgres DB. If I try to run without sessions adapter enable it runs perfectly. 

`error: sails-pg-session#PostSQLStore -  error: password authentication failed for user 'my_user'
    at Connection.parseE (/etc/zebu-app/electron-release-server/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/etc/zebu-app/electron-release-server/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/etc/zebu-app/electron-release-server/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)`

local.js file contains the right parameters for the remote db

` session: {
    database: 'mydb',
    host: '192.168.110.150',
    user: 'my_user',
    password: 'password',
    port: 5432
  },
`
Node Version: 7.2.0
Npm Version: 5.0.3

Any ideas of what this might be?

**Comment by jjprestes** [comment]
I fixed that by updating pg dependency from sails-pg-session to the latest (6.4.0)

**Comment by miraclesumail** [comment]
upstairs cheat me ??latest (6.4.0)  funny?

**Comment by gliss** [comment]
@jjprestes 
> I fixed that by updating pg dependency from sails-pg-session to the latest (6.4.0)

I tried this and now i get the following error:
```
error: A hook (`session`) failed to load!
error: Could not load Connect session adapter :: sails-pg-session

TypeError: Cannot read property 'Store' of undefined
    at module.exports (E:\admin\Documents\Repos\electron-release-server\node_modules\sails-pg-session\lib\sails-pg-session.js:24:31)
    at Hook.initialize (E:\admin\Documents\Repos\electron-release-server\node_modules\sails\lib\hooks\session\index.js:222:35)
    at Hook.wrapper [as initialize] (E:\admin\Documents\Repos\electron-release-server\node_modules\@sailshq\lodash\lib\index.js:3275:19)
    at E:\admin\Documents\Repos\electron-release-server\node_modules\sails\lib\hooks\index.js:88:16
    at E:\admin\Documents\Repos\electron-release-server\node_modules\sails\node_modules\async\lib\async.js:52:16
    at E:\admin\Documents\Repos\electron-release-server\node_modules\sails\node_modules\async\lib\async.js:548:17
    at E:\admin\Documents\Repos\electron-release-server\node_modules\sails\node_modules\async\lib\async.js:542:17
    at _arrayEach (E:\admin\Documents\Repos\electron-release-server\node_modules\sails\node_modules\async\lib\async.js:85:13)
    at Immediate.taskComplete [as _onImmediate] (E:\admin\Documents\Repos\electron-release-server\node_modules\sails\node_modules\async\lib\async.js:541:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)


error: A hook (`orm`) failed to load!
```
