### ISSUE TITLE
Error on Server start

### ISSUE THREAD

**Issue by mathe42** [ArekSredzki/electron-release-server#142]
When I run `npm start` I getthis error:

(in Windows and Ubuntu)
```
`include-all` attempted to `require(/root/electron-release-server/config/docker.js)`, but an error occurred::
Details:TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/root/electron-release-server/config/docker.js:28:66)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /root/electron-release-server/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:271:33
    at Array.forEach (native)
    at _recursivelyIncludeAll (/root/electron-release-server/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:174:11)
    at includeAll (/root/electron-release-server/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:292:5)
    at helpBuildDictionary (/root/electron-release-server/node_modules/sails/node_modules/include-all/lib/help-build-dictionary.js:43:15)
    at Function.module.exports.aggregate (/root/electron-release-server/node_modules/sails/node_modules/include-all/index.js:101:10)
    at Array.loadOtherConfigFiles (/root/electron-release-server/node_modules/sails/lib/hooks/moduleloader/index.js:247:22)
    at /root/electron-release-server/node_modules/sails/node_modules/async/lib/async.js:591:38
    at _arrayEach (/root/electron-release-server/node_modules/sails/node_modules/async/lib/async.js:85:13)
    at Object.async.auto (/root/electron-release-server/node_modules/sails/node_modules/async/lib/async.js:552:9)
    at Hook.loadUserConfig (/root/electron-release-server/node_modules/sails/lib/hooks/moduleloader/index.js:245:13)
    at Hook.wrapper [as loadUserConfig] (/root/electron-release-server/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at Hook.loadModules (/root/electron-release-server/node_modules/sails/lib/hooks/userconfig/index.js:41:27)
    at Hook.wrapper [as loadModules] (/root/electron-release-server/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at Array.async.auto.modules (/root/electron-release-server/node_modules/sails/lib/hooks/index.js:79:27)
```

**Comment by deviant32** [comment]
Same thing for me running Node 6.4.0

**Comment by deviant32** [comment]
It looks like it's looking for a postgresql host url.

**Comment by jlpellicer** [comment]
Same here, MacOS Sierra 10.12.6, npm 5.2.0, node 8.1.4, after setting up `config/local.js`

**Comment by deviant32** [comment]
set the DATABASE_URL as a environment variable and it will work.  This is your full postgres connection string.

**Comment by BattlefieldTsk** [comment]
Same here, Debian Strech 9.1, node 6.11.2, npm 3.10.10.

Resolve if delete config/docker.js file or set the DATABASE_URL and run **sudo npm start**.

**Comment by lastingman** [comment]
same issue here.
I set the DATABASE_URL, it is still not working.

**Comment by TongDaDa** [comment]
Same here. but I don't find a way.

**Comment by DustinBrett** [comment]
I've submitted a [PR](https://github.com/ArekSredzki/electron-release-server/pull/209) that may help.
