### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by eridal** [ArekSredzki/electron-release-server#16]
Hi all,

We are getting this error for Win32 releases. It works just fine for OSX.

We have:
- v0.2.0: our baseline
- v0.2.1: release we are baking

We have uploaded the `.exe` files to each version. These are present at the Download page and we were able to manually download them.

An pointers will be greatly appreciated.

---

##### For version 0.1.9
```
$ http get "http://$host/update/win32/0.1.9"

HTTP/1.1 500 Internal Server Error
{
    "message": "Cannot read property 'name' of undefined", 
    "stack": "TypeError: Cannot read property 'name' of undefined at /api/controllers/VersionController.js:125:62
    at tryCatcher (/node_modules/waterline/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/node_modules/waterline/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/node_modules/waterline/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/node_modules/waterline/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/node_modules/waterline/node_modules/bluebird/js/release/promise.js:676:18)
    at Promise._fulfill (/node_modules/waterline/node_modules/bluebird/js/release/promise.js:617:18)
    at /node_modules/waterline/node_modules/bluebird/js/release/nodeback.js:42:21
    at wrapper (/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at callback.success (/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at returnResults (/node_modules/waterline/lib/waterline/query/finders/basic.js:392:9)
    at /node_modules/waterline/lib/waterline/query/finders/basic.js:277:16
    at /node_modules/waterline/lib/waterline/query/finders/operations.js:78:46
    at wrapper (/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at callback.success (/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at /node_modules/sails-postgresql/lib/adapter.js:1469:16"
}
```

##### For version 0.2.0 and 0.2.1
```
$ http get "http://$host/update/win32/0.2.0"

HTTP/1.1 204 No Content

(empty body)
```

**Comment by ArekSredzki** [comment]
Hi @eridal, please include the version of `electron-release-server` you're working from.
Also, please rebase on the latest one.

FYI, Squirrel.Windows does not use the normal endpoint, it instead it uses `platform/version/RELEASES`

**Comment by ArekSredzki** [comment]
@eridal care to provide an update?

**Comment by eridal** [comment]
Hi @ArekSredzki,

Please excuse such delayed response.
I was still not able to find time to find these values, but I will make sure to send these over the week.

We found that we need to add the versions in the right history-order to make it work. I have moved to work in another area, but I should be back soon.

Will keep you posted.

**Comment by ArekSredzki** [comment]
Hi @eridal no worries. All of these issues have been fixed in more recent versions. Please rebase your fork. Let me know if you have any issues :)
