### ISSUE TITLE
There was an error starting the service

### ISSUE THREAD

**Issue by saatana97** [ArekSredzki/electron-release-server#175]
Several warnings appear when I run the "npm install" command（As shown below）
Then I ran "npm start" error:TypeError: done is not a function
I found in the api / hooks / myHook / index.js: 20 definition of the configure function needs a function as its argument.
However, in node_modules \ _sails @ 0.12.14 @ sails \ lib \ app \ private \ loadHooks.js: 170, it was found that there was no parameter passed to configure function to call exception
------------------
error: TypeError: done is not a function
    at Hook.configure (D:\nodejs\seed\api\hooks\myHook\index.js:20:14)
    at Hook.wrapper [as configure] (D:\nodejs\seed\node_modules\_@sailshq_lodash@3.10.2@@sailshq\lodash\lib\index.js:3250:19)
    at D:\nodejs\seed\node_modules\_sails@0.12.14@sails\lib\app\private\loadHooks.js:170:20
    at D:\nodejs\seed\node_modules\_async@1.5.0@async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (D:\nodejs\seed\node_modules\_async@1.5.0@async\lib\async.js:233:13)
    at Object.async.forEach.async.each (D:\nodejs\seed\node_modules\_async@1.5.0@async\lib\async.js:209:22)
    at configure (D:\nodejs\seed\node_modules\_sails@0.12.14@sails\lib\app\private\loadHooks.js:167:17)
    at D:\nodejs\seed\node_modules\_async@1.5.0@async\lib\async.js:713:13
    at iterate (D:\nodejs\seed\node_modules\_async@1.5.0@async\lib\async.js:262:13)
    at D:\nodejs\seed\node_modules\_async@1.5.0@async\lib\async.js:274:29
    at D:\nodejs\seed\node_modules\_async@1.5.0@async\lib\async.js:44:16
    at D:\nodejs\seed\node_modules\_async@1.5.0@async\lib\async.js:718:17
    at D:\nodejs\seed\node_modules\_async@1.5.0@async\lib\async.js:167:37
    at D:\nodejs\seed\node_modules\_async@1.5.0@async\lib\async.js:52:16
    at done (D:\nodejs\seed\node_modules\_async@1.5.0@async\lib\async.js:246:17)
    at D:\nodejs\seed\node_modules\_async@1.5.0@async\lib\async.js:44:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
![tim 20171219180045](https://user-images.githubusercontent.com/34677730/34151567-9c6caca4-e4e6-11e7-8b4d-35b1aefb4a53.png)

**Comment by saatana97** [comment]
closed,I do not know why....
