### ISSUE TITLE
Error on server start  - bootstrap.js

### ISSUE THREAD

**Issue by AzharHusain** [ArekSredzki/electron-release-server#186]
I am getting following error while starting server...
```
`include-all` attempted to `require(F:\SRDALS\Application Code\electron-release-server\config\bootstrap.js)`, but an error occurred::
Details:F:\SRDALS\Application Code\electron-release-server\config\bootstrap.js:1210

^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at F:\SRDALS\Application Code\electron-release-server\node_modules\sails\node_modules\include-all\lib\help-include-all-sync.js:271:33
    at Array.forEach (<anonymous>)
    at _recursivelyIncludeAll (F:\SRDALS\Application Code\electron-release-server\node_modules\sails\node_modules\include-all\lib\help-include-all-sync.js:174:11)
    at includeAll (F:\SRDALS\Application Code\electron-release-server\node_modules\sails\node_modules\include-all\lib\help-include-all-sync.js:292:5)
    at helpBuildDictionary (F:\SRDALS\Application Code\electron-release-server\node_modules\sails\node_modules\include-all\lib\help-build-dictionary.js:43:15)
    at Function.module.exports.aggregate (F:\SRDALS\Application Code\electron-release-server\node_modules\sails\node_modules\include-all\index.js:101:10)
    at Array.loadOtherConfigFiles (F:\SRDALS\Application Code\electron-release-server\node_modules\sails\lib\hooks\moduleloader\index.js:247:22)
    at F:\SRDALS\Application Code\electron-release-server\node_modules\sails\node_modules\async\lib\async.js:591:38
    at _arrayEach (F:\SRDALS\Application Code\electron-release-server\node_modules\sails\node_modules\async\lib\async.js:85:13)
    at Object.async.auto (F:\SRDALS\Application Code\electron-release-server\node_modules\sails\node_modules\async\lib\async.js:552:9)
    at Hook.loadUserConfig (F:\SRDALS\Application Code\electron-release-server\node_modules\sails\lib\hooks\moduleloader\index.js:245:13)
    at Hook.wrapper [as loadUserConfig] (F:\SRDALS\Application Code\electron-release-server\node_modules\@sailshq\lodash\lib\index.js:3275:19)
    at Hook.loadModules (F:\SRDALS\Application Code\electron-release-server\node_modules\sails\lib\hooks\userconfig\index.js:41:27)
npm ERR! code ELIFECYCLE
```

Along with this I couldn't find any documentation stating of what to be filled for field mentioned below, will it be path or just directory name. What is it purpose and where should I create this directory?
```
files: {
    // Folder must exist and user running the server must have adequate perms
    dirname: 'PATH_FOR_ASSETS',
    // Maximum allowed file size in bytes
    // Defaults to 500MB
    // maxBytes: 524288000
  }
```

**Comment by joshuapinter** [comment]
I'm getting the same thing. The quick start is not working.

**Comment by ArekSredzki** [comment]
Were you ever able to resolve this? If not I'll close this in some time.
