### ISSUE TITLE
 relation "public.channel" does not exist when running npm start.

### ISSUE THREAD

**Issue by mgara** [ArekSredzki/electron-release-server#190]
Following the **deploy** guide, I faced this problem, it might be the documentation is missing some _database migration_ step.

```
Bootstrap encountered an error: (see below)
Error (E_UNKNOWN) :: Encountered an unexpected error
error: relation "public.channel" does not exist
    at Connection.parseE (/opt/livescale/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/opt/livescale/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/opt/livescale/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)

Details:  error: relation "public.channel" does not exist

```

**Comment by NicolaConnect** [comment]
Hey mgara,
As stated on issue #67, please set the environment to development and then run npm start. After that, put it in production mode and it should work!

**Comment by mgara** [comment]
Hey Nicola, thanks for the answer, 
Still have the issue (checkout out the code again, clean install ) still have the same issue.

node -v
v8.12.0

npm -v
6.4.1

**Comment by mgara** [comment]
I moved the **config/docker.js** to /tmp directory, started in **devel** env. looks like the app wants to load the **docker.js**
