### ISSUE TITLE
A series of errors when I start it.

### ISSUE THREAD

**Issue by TongDaDa** [ArekSredzki/electron-release-server#198]
I have copy the local.template to the equative directory(no any file change), and then I run the command of `npm start`, It has thrown an error that says the `DATABASE_URL` env is not found, cause a split function to execute into error. About the error information below:

```
`include-all` attempted to `require(/Users/liutong/Desktop/projects/source_code/electron-release-server/config/docker.js)`, but an error occurred:: 
Details:TypeError: Cannot read property 'split' of undefined
```

And then I deleted it, but throw another error below.

**ErrorInfo**
```
error: Error: getaddrinfo ENOTFOUND 127.0.0.1:5000 127.0.0.1:5000:5432
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)

Error creating a connection to Postgresql using the following settings:
 { host: '127.0.0.1:5000',
  port: 5432,
  schema: true,
  ssl: false,
  adapter: 'sails-postgresql',
  user: 'releaseserver',
  password: '[redacted]',
  database: 'releaseserver',
  identity: 'postgresql' }

* * *
Complete error details:
 { Error: getaddrinfo ENOTFOUND 127.0.0.1:5000 127.0.0.1:5000:5432
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '127.0.0.1:5000',
  host: '127.0.0.1:5000',
  port: 5432 }


Troubleshooting tips:

 -> You appear to be trying to use a Postgresql install on localhost. Maybe the database server isn't running, or is not installed?

 -> Is your Postgresql configuration correct?  Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10. To override default settings, specify the desired properties on the relevant Postgresql "connection" config object where the host/port/database/etc. are configured. If you're using Sails, this is generally located in `config/connections.js`, or wherever your environment-specific database configuration is set.

 -> Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10
``

**Comment by miraclesumail** [comment]
yes meet same problem,  cannnot connect to PostgreSQL why

**Comment by gliss** [comment]
@TongDaDa you appear to have put two ports in your connection. You have 5000 at the end of local heat and then you have port 5432.

For the first error try setting an environment variable, it will depend on your operating system but linux is
```
export DATABASE_URL=postgresql://user:password@localhost:5432
```

**Comment by DustinBrett** [comment]
I've submitted a [PR](https://github.com/ArekSredzki/electron-release-server/pull/209) that may help.
