### ISSUE TITLE
Nginx doesn't connect to electron-release-server localhost

### ISSUE THREAD

**Issue by Malnasser** [ArekSredzki/electron-release-server#200]
Hello,

I'm front-end developer and I just started learning how to run web-server. I set up electron-release-server and Nginx configuration (check below for code),  but when look up the server I get this error:

**ERROR**
```
An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.
```

inside the browser console: 
```
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
```

**Here Is a punch of info you may need guys**

website.conf: (nginx)
```
########################################
# HTTPS server at 443 serving up the UI.
#
# To be accessed directly by clients.
########################################
server {
    if ($host !~* 'iris') {
      return 301 https://www.website.com$request_uri;
    }
    access_log  /var/log/nginx/ui_443_access.log;
    error_log   /var/log/nginx/ui_443_error.log;
    index       index.html;
down for maintenance
    root       [removed]
    listen      443 ssl default_server;
    server_name website.com;

    ### ssl config ###
    ssl_certificate           /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key       /etc/nginx/ssl/nginx.key;
    ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers               !RC4:HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    keepalive_timeout         100;
    ssl_session_cache         shared:SSL:10m;
    ssl_session_timeout       10m;
    ## OCSP Stapling
    resolver 127.0.0.1;
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /etc/nginx/ssl/nginx.ca-bundle;

    gzip             on;
    #gzip_min_length  1000;
    gzip_http_version 1.1;


    location /api {
        include uwsgi_params;
        uwsgi_pass [delete];
        #try_files $uri $uri/ /index.html;
    }

    location /electron {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_pass https://localhost:1337;
    }

    # serve static
    location / {
        #internal;
        #root [removed];
        try_files $uri $uri/ /index.html;
    }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```
local.js:

```
var fs = require('fs');
module.exports = {
  appUrl: 'http://localhost:1337',

  auth: {
    static: {
      username: '[removed]',
      password: '[removed]'
    },

  jwt: {
    token_secret: '[removed]'
  },

  connections: {
    postgresql: {
      adapter: 'sails-postgresql',
      host: 'localhost',
      user: '[removed]',
      password: '[removed]',
      database: 'electron_release_server'
    }
  },

  session: {
    secret: '[removed]',
    database: 'electron_release_server',
    host: 'localhost',
    user: '[removed]',
    password: '[removed]',
    port: 5432
  },

  files: {
    dirname: __dirname + 'assets/release_assets'
  },
  environment: process.env.NODE_ENV || 'development'
};
```

running : `netstat -lpn`
```
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -
tcp6       0      0 ::1:5432                :::*                    LISTEN      -
tcp6       0      0 :::1337                 :::*                    LISTEN      1789/node 
```

running error.log for nginx
```
2019/08/14 15:07:34 [error] 4840#4840: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2019/08/14 15:07:34 [error] 4840#4840: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2019/08/14 15:07:39 [error] 4840#4840: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2019/08/14 15:07:44 [error] 4840#4840: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2019/08/14 15:07:49 [error] 4840#4840: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2019/08/14 15:07:54 [error] 4840#4840: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2019/08/14 15:07:59 [error] 4840#4840: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2019/08/14 15:08:04 [error] 4840#4840: ocsp.comodoca.com could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.comodoca.com, certificate: "/etc/nginx/ssl/nginx.crt"
```

**Comment by servappio** [comment]
Hey there, take a look at this topic https://serverfault.com/questions/939244/send-failed-111-connection-refused-while-resolving-resolver-127-0-0-153 possibly an issue with your server DNS and the SSL resolver

**Comment by gliss** [comment]
Hey there, take a look at this topic https://serverfault.com/questions/939244/send-failed-111-connection-refused-while-resolving-resolver-127-0-0-153 possibly an issue with your server DNS and the SSL resolver

**Comment by Malnasser** [comment]
@gliss  Thansk Thanks! 

I fixed the previous error but I ended up with another error message in nginx error.log

```
2019/08/15 20:42:42 [error] 2096#2096: *1 upstream prematurely closed connection while reading response header from upstream, client: 66.17.114.144, server: iris.query.ai, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:1337/", host: "iris.query.ai"
2019/08/15 20:42:42 [error] 2096#2096: *1 upstream prematurely closed connection while reading response header from upstream, client: 66.17.114.144, server: iris.query.ai, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:1337/favicon.ico", host: "iris.query.ai", referrer: "http://iris.query.ai/"
```

**Comment by Malnasser** [comment]
Thanks error solved but I ended up with another error with sessions:
```
0|app  | sails-pg-session#get -  error: function sails_session_store_get(unknown) does not exist
0|app  |     at Connection.parseE (/opt/queryai/electron-release-server/node_modules/pg/lib/connection.js:539:11)
0|app  |     at Connection.parseMessage (/opt/queryai/electron-release-server/node_modules/pg/lib/connection.js:366:17)
0|app  |     at Socket.<anonymous> (/opt/queryai/electron-release-server/node_modules/pg/lib/connection.js:105:22)
0|app  |     at emitOne (events.js:116:13)
0|app  |     at Socket.emit (events.js:211:7)
0|app  |     at addChunk (_stream_readable.js:263:12)
0|app  |     at readableAddChunk (_stream_readable.js:250:11)
0|app  |     at Socket.Readable.push (_stream_readable.js:208:10)
0|app  |     at TCP.onread (net.js:601:20)
0|app  | Error occurred in session middleware :: 'error: function sails_session_store_get(unknown) does not exist\n    at Connection.parseE (/opt/queryai/electron-release-server/node_modules/pg/lib/connection.js:539:11)\n    at Connection.parseMessage (/opt/queryai/electron-release-server/node_modules/pg/lib/connection.js:366:17)\n    at Socket.<anonymous> (/opt/queryai/electron-release-server/node_modules/pg/lib/connection.js:105:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)'
```

**Comment by gliss** [comment]
Check that you have sails-pg-session install in the node_modules folder.
