### ISSUE TITLE
Publishing with Electron Forge no longer works

### ISSUE THREAD

**Issue by gliss** [ArekSredzki/electron-release-server#211]
Since 1.5.0 publishing via electron forge no longer works. I expect this is due to the new flavor feature and the flavor name included at the end of the file name on upload.

**Comment by DustinBrett** [comment]
I will look into this asap. Are there any specific errors that you are getting? Also can you clarify where you are seeing `flavor name included at the end of the file name on upload`?

**Comment by DustinBrett** [comment]
The flavor logic was setup with the intention that all the old endpoints could still be used and that flavor would just default to `default`. So if this is not occurring in this instance I will fix it. All recent changes should be backwards compatible.

**Note**: All that being said, you will need to migrate the database to accommodate the changes in the models.

**Comment by gliss** [comment]
Doing some investigating now will update soon.

**Comment by gliss** [comment]
As a note electron-forge finishes without any errors

**Comment by DustinBrett** [comment]
> As a note electron-forge finishes without any errors

Okay, good to know. Any errors you are able to generate, please provide so I can narrow down my search for a fix. Thanks.

**Comment by gliss** [comment]
Things i've noticed so far

- No errors from electron forge
- Electron forge finishes quickly
- There are POST calls to the server
- No new entries in database

**Comment by DustinBrett** [comment]
> Things i've noticed so far
> 
> * No errors from electron forge
> * Electron forge finishes quickly
> * There are POST calls to the server
> * No errors thrown by nginx
> * No new entries in database

Is there anything coming from the node console where electron release server is running? Have you ran the migration scripts and did they have any issues?

**Comment by gliss** [comment]
Yes Migration scripts have been run. I can manually create the version and upload files. Attached image of console from server.

![image](https://user-images.githubusercontent.com/7798937/66277644-e94cb880-e8fd-11e9-9eb8-8455b5962670.png)

**Comment by DustinBrett** [comment]
Ok, I will setup electron forge and test this tomorrow.

It will be interesting to see what data it's posting and to what endpoint.

Perhaps I need to add flavor into the provided version object when it's missing during publish, or a beforeCreate on the model and remove required restriction on flavor.

Sorry for the inconvenience, I'll get to the bottom of this error either way. I'm glad manual creation and migration worked for you at least.

**Comment by gliss** [comment]
Thanks, not a problem, appreciate all the updates you are doing. I'll keep testing and post updates.

**Comment by gliss** [comment]
Using postman I tried to POST a file using data from uploading via the admin page and worked successfully.
 Trying again but removing the '_default' (I'm guessing this is what electron forge sends) from the version errors.

```
{
  "invalidAttributes": {
    "name": [
      {
        "rule": "string",
        "message": "Value should be a string (instead of null, which is an object)"
      },
      {
        "rule": "required",
        "message": "\"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined"
      }
    ],
    "channel": [
      {
        "rule": "required",
        "message": "\"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined"
      }
    ],
    "availability": [
      {
        "rule": "datetime",
        "message": "Value should be a datetime (instead of null, which is an object)"
      },
      {
        "rule": "required",
        "message": "\"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined"
      }
    ],
    "flavor": [
      {
        "rule": "required",
        "message": "\"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined"
      }
    ]
  },
  "model": "Version",
  "_e": {},
  "rawStack": "    at WLValidationError.WLError (/var/www/node_modules/waterline/lib/waterline/error/WLError.js:25:15)\n    at new WLValidationError (/var/www/node_modules/waterline/lib/waterline/error/WLValidationError.js:19:28)\n    at _afterValidating (/var/www/node_modules/waterline/lib/waterline/query/validate.js:53:23)\n    at allValidationsChecked (/var/www/node_modules/waterline/lib/waterline/core/validations.js:265:12)\n    at /var/www/node_modules/waterline/node_modules/async/lib/async.js:52:16\n    at Object.async.forEachOf.async.eachOf (/var/www/node_modules/waterline/node_modules/async/lib/async.js:236:30)\n    at Object.async.forEach.async.each (/var/www/node_modules/waterline/node_modules/async/lib/async.js:209:22)\n    at module.exports.Validator.validate (/var/www/node_modules/waterline/lib/waterline/core/validations.js:144:9)\n    at /var/www/node_modules/waterline/lib/waterline/query/validate.js:42:25\n    at /var/www/node_modules/waterline/node_modules/async/lib/async.js:718:13\n    at Immediate.iterate [as _onImmediate] (/var/www/node_modules/waterline/node_modules/async/lib/async.js:262:13)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)\n    at process.topLevelDomainCallback (domain.js:126:23)",
  "reason": "4 attributes are invalid",
  "code": "E_VALIDATION",
  "status": 400,
  "details": "Invalid attributes sent to Version:\n • name\n   • Value should be a string (instead of null, which is an object)\n   • \"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined\n • channel\n   • \"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined\n • availability\n   • Value should be a datetime (instead of null, which is an object)\n   • \"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined\n • flavor\n   • \"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined\n",
  "message": "[Error (E_VALIDATION) 4 attributes are invalid] Invalid attributes sent to Version:\n • name\n   • Value should be a string (instead of null, which is an object)\n   • \"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined\n • channel\n   • \"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined\n • availability\n   • Value should be a datetime (instead of null, which is an object)\n   • \"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined\n • flavor\n   • \"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined\n",
  "stack": "Error (E_VALIDATION) :: 4 attributes are invalid\n    at WLValidationError.WLError (/var/www/node_modules/waterline/lib/waterline/error/WLError.js:25:15)\n    at new WLValidationError (/var/www/node_modules/waterline/lib/waterline/error/WLValidationError.js:19:28)\n    at _afterValidating (/var/www/node_modules/waterline/lib/waterline/query/validate.js:53:23)\n    at allValidationsChecked (/var/www/node_modules/waterline/lib/waterline/core/validations.js:265:12)\n    at /var/www/node_modules/waterline/node_modules/async/lib/async.js:52:16\n    at Object.async.forEachOf.async.eachOf (/var/www/node_modules/waterline/node_modules/async/lib/async.js:236:30)\n    at Object.async.forEach.async.each (/var/www/node_modules/waterline/node_modules/async/lib/async.js:209:22)\n    at module.exports.Validator.validate (/var/www/node_modules/waterline/lib/waterline/core/validations.js:144:9)\n    at /var/www/node_modules/waterline/lib/waterline/query/validate.js:42:25\n    at /var/www/node_modules/waterline/node_modules/async/lib/async.js:718:13\n    at Immediate.iterate [as _onImmediate] (/var/www/node_modules/waterline/node_modules/async/lib/async.js:262:13)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)\n    at process.topLevelDomainCallback (domain.js:126:23)"
}
```

**Comment by DustinBrett** [comment]
I've created a [PR](https://github.com/ArekSredzki/electron-release-server/pull/214) to deal with this issue hopefully.

I setup Electron Forge and there were indeed some issues with publishing. It doesn't provide `availability` or `flavor` and it shouldn't have to, so I have adjusted those requirements in the Version model. Then when it goes to add the asset it tries to use the version name and not the id, so I have added a check when creating assets to handle this case of version not including flavor. In my tests this allowed publishing to work via Electron Forge.

**Comment by gliss** [comment]
Great thanks @DustinBrett will test once merged

**Comment by ArekSredzki** [comment]
It has merged :)

**Comment by gliss** [comment]
Working perfectly, cheers team.
