### ISSUE TITLE
not work with PG 12

### ISSUE THREAD

**Issue by roytan883** [ArekSredzki/electron-release-server#223]
After upgrade PG to 12, this error show:
```
error: A hook (`orm`) failed to load!
error: error: column r.consrc does not exist
    at Connection.parseE (/home/rtsu/rts-pc-update/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/rtsu/rts-pc-update/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/rtsu/rts-pc-update/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
```

**Comment by ArekSredzki** [comment]
@DustinBrett Would you be able to look at this?

**Comment by ArekSredzki** [comment]
This issue has been avoided by specifying that PG 11 should be used
