### ISSUE TITLE
A hook (`orm`) failed to load!

### ISSUE THREAD

**Issue by hanjt** [ArekSredzki/electron-release-server#224]
```module.exports = {

  // The full base url at which your site will be primarily available.
  // Include an http:// prefix
  // ex. 'http://my-site.com'
  appUrl: 'http://localhost',

  auth: {
    // Provide a set of credentials that can be used to access the admin interface.
    static: {
      username: 'postgres',
      password: 'xxxx'
    },
    // You can also specify an ldap connection that can be used for authentication.
    //ldap: {
    //  usernameField: 'USERNAME_FIELD', // Key at which the username is stored
    //  server: {
    //    url: 'ldap://LDAP_SERVER_FQDN:389',
    //    bindDn: 'INSERT_LDAP_SERVICE_ACCOUNT_USERNAME_HERE',
    //    bindCredentials: 'INSERT_PASSWORD_HERE',
    //    searchBase: 'USER_SEARCH_SPACE', // ex: ou=Our Users,dc=companyname,dc=com
    //    searchFilter: '(USERNAME_FIELD={{username}})'
    //  }
    //}
  },

  jwt: {
    // Recommended: 63 random alpha-numeric characters for secret
    // Generate using: https://www.grc.com/passwords.htm
    token_secret: 'xxxx'
  },

  connections: {
    postgresql: {
      adapter: 'sails-postgresql',
      host: 'localhost',
      user: 'electron_release_server_user',
      password: 'xxxx',
      database: 'electron_release_server'
    }
  },

  session: {
    // Recommended: 63 random alpha-numeric characters for secret
    // Generate using: https://www.grc.com/passwords.htm
    secret: 'xxxx',
    database: 'electron_release_server',
    host: 'localhost',
    user: 'electron_release_server_user',
    password: 'xxxx',
    port: 5432
  },

  files: {
    // Folder must exist and user running the server must have adequate perms
    dirname: '/Users/xxx/Library/Application\\ Support/Postgres/var-12',
    // Maximum allowed file size in bytes
    // Defaults to 500MB
    // maxBytes: 524288000
  }
```

The file of local.js like this.  But run  `npm start` has some errors.
```
> electron-release-server@1.5.2 start /Users/hanjiatong/Documents/electron-release-server
> node app.js

error: A hook (`orm`) failed to load!
error: error: column r.consrc does not exist
    at Connection.parseE (/Users/hanjiatong/Documents/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/hanjiatong/Documents/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/hanjiatong/Documents/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

```

**Comment by gliss** [comment]
When I had this issue I removed the dependency sails-pg-session and added v2land-sails-pg-session. sails-pg-session had an outdated dependency which caused issues with hooks.
