### ISSUE TITLE
Upgrade package.json

### ISSUE THREAD

**Issue by devlerone** [ArekSredzki/electron-release-server#227]
Hello everybody

I'm new here and wanted to set up a test server, but I keep coming across one bug after another. Is there any chance to upgrade dependencies/package.json etc.? Even when I update everything, npm shows me 6 vulnerabilities with this master (3 low, 3 high)

right now I'm at error:

`TypeError: Cannot read property 'Store' of undefined
    at module.exports (C:\update-server\node_modules\sails-pg-session\lib\sails-pg-session.js:24:31)
    at afterMaybeConnectToRedis (C:\update-server\node_modules\sails\lib\hooks\session\index.js:405:33)
    at maybeConnectToRedis (C:\update-server\node_modules\sails\lib\hooks\session\index.js:295:22)
    at setupAdapter (C:\update-server\node_modules\sails\lib\hooks\session\index.js:353:13)
    at Hook.initialize (C:\update-server\node_modules\sails\lib\hooks\session\index.js:435:9)
    at Hook.wrapper [as initialize] (C:\update-server\node_modules\@sailshq\lodash\lib\index.js:3282:19)
    at C:\update-server\node_modules\sails\lib\hooks\index.js:122:20
    at C:\update-server\node_modules\sails\node_modules\async\dist\async.js:421:16
    at processQueue (C:\update-server\node_modules\sails\node_modules\async\dist\async.js:1565:20)
    at taskComplete (C:\update-server\node_modules\sails\node_modules\async\dist\async.js:1588:9)
    at C:\update-server\node_modules\sails\node_modules\async\dist\async.js:1612:17
    at C:\update-server\node_modules\sails\node_modules\async\dist\async.js:906:16
    at Hook.loadModules (C:\update-server\node_modules\sails\lib\hooks\index.js:178:14)
    at Hook.wrapper [as loadModules] (C:\update-server\node_modules\@sailshq\lodash\lib\index.js:3282:19)
    at modules (C:\update-server\node_modules\sails\lib\hooks\index.js:86:25)
    at runTask (C:\update-server\node_modules\sails\node_modules\async\dist\async.js:1621:13)
    at C:\update-server\node_modules\sails\node_modules\async\dist\async.js:1559:13
    at processQueue (C:\update-server\node_modules\sails\node_modules\async\dist\async.js:1569:13)
    at Object.auto (C:\update-server\node_modules\sails\node_modules\async\dist\async.js:1555:5)
    at Hook.load (C:\update-server\node_modules\sails\lib\hooks\index.js:80:13)
    at Hook.wrapper [as load] (C:\update-server\node_modules\@sailshq\lodash\lib\index.js:3282:19)
    at loadHook (C:\update-server\node_modules\sails\lib\app\private\loadHooks.js:212:17)
---`

my globals.js setting:
`module.exports.globals = {
	_: false,
	async: false,
	sails: true,
	services: true,
	models: true
};`

**Comment by gliss** [comment]
I remember getting this error but unfortunately not what I did to remedy it. If it helps i removed the use of the required version of sails-pg-session and opted for v2land-sails-pg-session instead and it helped with a few sail-pg errors.
