### ISSUE TITLE
no pg_hba.conf entry for host

### ISSUE THREAD

**Issue by ScribbleNerd** [ArekSredzki/electron-release-server#245]
When trying to setup electron release server, I get the following issue, and I'm not quite sure what it means or how to fix it. I've tried googling the issue already and couldn't find anything helpful

I'm running in a docker container, but this happens when just running normally too
```
Error creating a connection to Postgresql using the following settings:
 {
  host: 'postgresql.db.host.ip',
  port: 5432,
  schema: true,
  ssl: false,
  adapter: 'sails-postgresql',
  user: 'username',
  password: '[redacted]',
  database: 'db',
  identity: 'postgresql'
}

* * *
Complete error details:
 error: no pg_hba.conf entry for host "electron.release.server.ip", user "username", database "db", SSL off
    at Connection.parseE (/usr/src/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/usr/src/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/usr/src/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 232,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file:
   'd:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\libpq\\auth.c',
  line: '520',
  routine: 'ClientAuthentication' }


Troubleshooting tips:

 -> Is your Postgresql configuration correct?  Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10. To override default settings, specify the desired properties on the relevant Postgresql "connection" config object where the host/port/database/etc. are configured. If you're using Sails, this is generally located in `config/connections.js`, or wherever your environment-specific database configuration is set.

 -> Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10.

 -> Do you have multiple Sails instances sharing the same Postgresql database? Each Sails instance may use up to the configured `poolSize` # of connections. Assuming all of the Sails instances are just copies of one another (a reasonable best practice) we can calculate the actual # of Postgresql connections used (C) by multiplying the configured `poolSize` (P) by the number of Sails instances (N). If the actual number of connections (C) exceeds the total # of **AVAILABLE** connections to your Postgresql database (V), then you have problems.  If this applies to you, try reducing your `poolSize` configuration. A reasonable `poolSize` setting would be V/N.

 -> Are you using an SSL-enabled Postgresql host like Heroku? Make sure to set `ssl` to `true` (see http://stackoverflow.com/a/22177218/486547)
```

**Comment by beliaev-maksim** [comment]
@ScribbleNerd 
please refer to #242 
see updated FAQ
