### ISSUE TITLE
permission denied for relation sails_session_store

### ISSUE THREAD

**Issue by Zhell1** [ArekSredzki/electron-release-server#247]
Hi, I managed to install electron-release-server with postgresql correctly, config everything and launch it. It launches fine and without any error.

But once I navigate to the pathURL it displays this error in the page & also appears in the console:

> **Error occurred in session middleware :: 'error: permission denied for relation sails_session_store**
>  at Connection.parseE (/home/user/electron-release-server/node_modules/v2land-sails-pg-session/node_modules/pg/lib/connection.js:567:11)
>  at Connection.parseMessage (/home/user/electron-release-server/node_modules/v2land-sails-pg-session/node_modules/pg/lib/connection.js:391:17)
>  at Socket. (/home/user/electron-release-server/node_modules/v2land-sails-pg-session/node_modules/pg/lib/connection.js:129:22)
>  at Socket.emit (events.js:198:13)
>  at Socket.EventEmitter.emit (domain.js:448:20)
>  at addChunk (_stream_readable.js:288:12)
>  at readableAddChunk (_stream_readable.js:269:11)
>  at Socket.Readable.push (_stream_readable.js:224:10)
>  at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)'

here is my config:

```
  connections: {
    postgresql: {
      adapter: 'sails-postgresql',
      host: 'localhost',
      user: 'electron_release_server_user',
      password: '[redacted]',
      database: 'electron_release_server'
    }
  },

  session: {
    // Recommended: 63 random alpha-numeric characters for secret
    // Generate using: https://www.grc.com/passwords.htm
    secret: '[redacted]',
    database: 'electron_release_server_sessions',
    host: 'localhost',
    user: 'electron_release_server_user',
    password: '[redacted]',
    port: 5432
  },

```

**Comment by Zhell1** [comment]
just solved it myself, it requires connecting to the postgreSQL database and doing:

`ALTER USER electron_release_server_user WITH SUPERUSER;`

would be useful to add to the docs !

By the way there is a mistake in the doc at https://github.com/ArekSredzki/electron-release-server/blob/master/docs/database.md
the session: database should be the _sessions version 

NOT THIS:
```
session: {
        database: 'electron_release_server'
```
BUT THIS:
```
session: {
        database: 'electron_release_server_sessions'
```
