### ISSUE TITLE
Unknown authenticationOk message typeMessage

### ISSUE THREAD

**Issue by plusflabby** [ArekSredzki/electron-release-server#256]
Hello,
I'm using the latest release and it's erroring out. Any help would be greatly appreciated!

```
> electron-release-server@1.5.2 start C:\Servers\Launcher Releases
> node app.js

C:\Servers\Launcher Releases\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:426
  throw new Error("Unknown authenticationOk message type" + util.inspect(msg));
  ^

Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 }
    at Connection.parseR (C:\Servers\Launcher Releases\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:426:9)
    at Connection.parseMessage (C:\Servers\Launcher Releases\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:345:17)
    at Socket.<anonymous> (C:\Servers\Launcher Releases\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:105:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:120:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-release-server@1.5.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-release-server@1.5.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by plusflabby** [comment]
I resolved this by changing the postgresql password encrypting to md5.
