### ISSUE TITLE
error: Error (E_UNKNOWN) :: Encountered an unexpected error

### ISSUE THREAD

**Issue by plusflabby** [ArekSredzki/electron-release-server#257]
Hello,
I am running the latest release of electron-release-server and am running into an error.
Any help would be greatly appreciated!
```
> electron-release-server@1.5.2 start C:\Servers\Launcher Releases
> node app.js

error: Bootstrap encountered an error: (see below)
error: Error (E_UNKNOWN) :: Encountered an unexpected error
: No find() method defined in adapter!
    at module.exports.find (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\adapter\dql.js:113:61)
    at module.exports._runOperation (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\query\finders\operations.js:411:29)
    at module.exports.run (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\query\finders\operations.js:70:8)
    at child.find (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\query\finders\basic.js:263:16)
    at child.wrapper [as find] (C:\Servers\Launcher Releases\node_modules\sails-hook-orm\node_modules\lodash\index.js:3095:19)
    at module.exports.Deferred.exec (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\query\deferred.js:485:16)
    at C:\Servers\Launcher Releases\config\bootstrap.js:25:14
    at nextTask (C:\Servers\Launcher Releases\node_modules\async\waterfall.js:16:14)
    at exports.default (C:\Servers\Launcher Releases\node_modules\async\waterfall.js:26:5)
    at C:\Servers\Launcher Releases\config\bootstrap.js:21:7
    at C:\Servers\Launcher Releases\node_modules\async\internal\map.js:27:9
    at replenish (C:\Servers\Launcher Releases\node_modules\async\internal\eachOfLimit.js:66:17)
    at C:\Servers\Launcher Releases\node_modules\async\internal\eachOfLimit.js:71:9
    at _asyncMap (C:\Servers\Launcher Releases\node_modules\async\internal\map.js:25:5)
    at C:\Servers\Launcher Releases\node_modules\async\internal\doParallelLimit.js:20:16
    at C:\Servers\Launcher Releases\node_modules\async\internal\doLimit.js:9:16
    at Version.find.availability (C:\Servers\Launcher Releases\config\bootstrap.js:20:11)
    at C:\Servers\Launcher Releases\node_modules\async\internal\parallel.js:31:39
    at replenish (C:\Servers\Launcher Releases\node_modules\async\internal\eachOfLimit.js:66:17)
    at C:\Servers\Launcher Releases\node_modules\async\internal\eachOfLimit.js:71:9
    at eachOfLimit (C:\Servers\Launcher Releases\node_modules\async\eachOfLimit.js:39:36)
    at C:\Servers\Launcher Releases\node_modules\async\internal\doLimit.js:9:16 {
  originalError: Error: No find() method defined in adapter!
      at module.exports.find (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\adapter\dql.js:113:61)
      at module.exports._runOperation (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\query\finders\operations.js:411:29)
      at module.exports.run (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\query\finders\operations.js:70:8)
      at child.find (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\query\finders\basic.js:263:16)
      at child.wrapper [as find] (C:\Servers\Launcher Releases\node_modules\sails-hook-orm\node_modules\lodash\index.js:3095:19)
      at module.exports.Deferred.exec (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\query\deferred.js:485:16)
      at C:\Servers\Launcher Releases\config\bootstrap.js:25:14
      at nextTask (C:\Servers\Launcher Releases\node_modules\async\waterfall.js:16:14)
      at exports.default (C:\Servers\Launcher Releases\node_modules\async\waterfall.js:26:5)
      at C:\Servers\Launcher Releases\config\bootstrap.js:21:7
      at C:\Servers\Launcher Releases\node_modules\async\internal\map.js:27:9
      at replenish (C:\Servers\Launcher Releases\node_modules\async\internal\eachOfLimit.js:66:17)
      at C:\Servers\Launcher Releases\node_modules\async\internal\eachOfLimit.js:71:9
      at _asyncMap (C:\Servers\Launcher Releases\node_modules\async\internal\map.js:25:5)
      at C:\Servers\Launcher Releases\node_modules\async\internal\doParallelLimit.js:20:16
      at C:\Servers\Launcher Releases\node_modules\async\internal\doLimit.js:9:16
      at Version.find.availability (C:\Servers\Launcher Releases\config\bootstrap.js:20:11)
      at C:\Servers\Launcher Releases\node_modules\async\internal\parallel.js:31:39
      at replenish (C:\Servers\Launcher Releases\node_modules\async\internal\eachOfLimit.js:66:17)
      at C:\Servers\Launcher Releases\node_modules\async\internal\eachOfLimit.js:71:9
      at eachOfLimit (C:\Servers\Launcher Releases\node_modules\async\eachOfLimit.js:39:36)
      at C:\Servers\Launcher Releases\node_modules\async\internal\doLimit.js:9:16,
  _e: Error: No find() method defined in adapter!
      at module.exports.find (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\adapter\dql.js:113:61)
      at module.exports._runOperation (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\query\finders\operations.js:411:29)
      at module.exports.run (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\query\finders\operations.js:70:8)
      at child.find (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\query\finders\basic.js:263:16)
      at child.wrapper [as find] (C:\Servers\Launcher Releases\node_modules\sails-hook-orm\node_modules\lodash\index.js:3095:19)
      at module.exports.Deferred.exec (C:\Servers\Launcher Releases\node_modules\waterline\lib\waterline\query\deferred.js:485:16)
      at C:\Servers\Launcher Releases\config\bootstrap.js:25:14
      at nextTask (C:\Servers\Launcher Releases\node_modules\async\waterfall.js:16:14)
      at exports.default (C:\Servers\Launcher Releases\node_modules\async\waterfall.js:26:5)
      at C:\Servers\Launcher Releases\config\bootstrap.js:21:7
      at C:\Servers\Launcher Releases\node_modules\async\internal\map.js:27:9
      at replenish (C:\Servers\Launcher Releases\node_modules\async\internal\eachOfLimit.js:66:17)
      at C:\Servers\Launcher Releases\node_modules\async\internal\eachOfLimit.js:71:9
      at _asyncMap (C:\Servers\Launcher Releases\node_modules\async\internal\map.js:25:5)
      at C:\Servers\Launcher Releases\node_modules\async\internal\doParallelLimit.js:20:16
      at C:\Servers\Launcher Releases\node_modules\async\internal\doLimit.js:9:16
      at Version.find.availability (C:\Servers\Launcher Releases\config\bootstrap.js:20:11)
      at C:\Servers\Launcher Releases\node_modules\async\internal\parallel.js:31:39
      at replenish (C:\Servers\Launcher Releases\node_modules\async\internal\eachOfLimit.js:66:17)
      at C:\Servers\Launcher Releases\node_modules\async\internal\eachOfLimit.js:71:9
      at eachOfLimit (C:\Servers\Launcher Releases\node_modules\async\eachOfLimit.js:39:36)
      at C:\Servers\Launcher Releases\node_modules\async\internal\doLimit.js:9:16,
  rawStack: ': No find() method defined in adapter!\n' +
    '    at module.exports.find (C:\\Servers\\Launcher Releases\\node_modules\\waterline\\lib\\waterline\\adapter\\dql.js:113:61)\n' +
    '    at module.exports._runOperation (C:\\Servers\\Launcher Releases\\node_modules\\waterline\\lib\\waterline\\query\\finders\\operations.js:411:29)\n' +
    '    at module.exports.run (C:\\Servers\\Launcher Releases\\node_modules\\waterline\\lib\\waterline\\query\\finders\\operations.js:70:8)\n' +
    '    at child.find (C:\\Servers\\Launcher Releases\\node_modules\\waterline\\lib\\waterline\\query\\finders\\basic.js:263:16)\n' +
    '    at child.wrapper [as find] (C:\\Servers\\Launcher Releases\\node_modules\\sails-hook-orm\\node_modules\\lodash\\index.js:3095:19)\n' +
    '    at module.exports.Deferred.exec (C:\\Servers\\Launcher Releases\\node_modules\\waterline\\lib\\waterline\\query\\deferred.js:485:16)\n' +
    '    at C:\\Servers\\Launcher Releases\\config\\bootstrap.js:25:14\n' +
    '    at nextTask (C:\\Servers\\Launcher Releases\\node_modules\\async\\waterfall.js:16:14)\n' +
    '    at exports.default (C:\\Servers\\Launcher Releases\\node_modules\\async\\waterfall.js:26:5)\n' +
    '    at C:\\Servers\\Launcher Releases\\config\\bootstrap.js:21:7\n' +
    '    at C:\\Servers\\Launcher Releases\\node_modules\\async\\internal\\map.js:27:9\n' +
    '    at replenish (C:\\Servers\\Launcher Releases\\node_modules\\async\\internal\\eachOfLimit.js:66:17)\n' +
    '    at C:\\Servers\\Launcher Releases\\node_modules\\async\\internal\\eachOfLimit.js:71:9\n' +
    '    at _asyncMap (C:\\Servers\\Launcher Releases\\node_modules\\async\\internal\\map.js:25:5)\n' +
    '    at C:\\Servers\\Launcher Releases\\node_modules\\async\\internal\\doParallelLimit.js:20:16\n' +
    '    at C:\\Servers\\Launcher Releases\\node_modules\\async\\internal\\doLimit.js:9:16\n' +
    '    at Version.find.availability (C:\\Servers\\Launcher Releases\\config\\bootstrap.js:20:11)\n' +
    '    at C:\\Servers\\Launcher Releases\\node_modules\\async\\internal\\parallel.js:31:39\n' +
    '    at replenish (C:\\Servers\\Launcher Releases\\node_modules\\async\\internal\\eachOfLimit.js:66:17)\n' +
    '    at C:\\Servers\\Launcher Releases\\node_modules\\async\\internal\\eachOfLimit.js:71:9\n' +
    '    at eachOfLimit (C:\\Servers\\Launcher Releases\\node_modules\\async\\eachOfLimit.js:39:36)\n' +
    '    at C:\\Servers\\Launcher Releases\\node_modules\\async\\internal\\doLimit.js:9:16',
  details: 'Details:  Error: No find() method defined in adapter!\n'
}
```

**Comment by Jake-Barrow** [comment]
@plusflabby We're having the same issue when initially setting up the release server, what did you do to fix this?

**Comment by plusflabby** [comment]
@Jake-Barrow I didn't fix it so I did something else.

**Comment by deepakkraju** [comment]
what is that something else?????????????
