### ISSUE TITLE
Error while running npm start

### ISSUE THREAD

**Issue by JohnProgrammer71** [ArekSredzki/electron-release-server#265]
Cannot run with npm start
I followed the deploy & database docs
```
C:\modding\.electron\SERVER>npm start

┌────────────────────────────────────────────────────────────┐
│                  npm update check failed                   │
│            Try running with sudo or get access             │
│            to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\jorda\.config │
└────────────────────────────────────────────────────────────┘

> electron-release-server@1.5.2 start C:\modding\.electron\SERVER
> node app.js

C:\modding\.electron\SERVER\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:426
  throw new Error("Unknown authenticationOk message type" + util.inspect(msg));
  ^

Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 }
    at Connection.parseR (C:\modding\.electron\SERVER\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:426:9)
    at Connection.parseMessage (C:\modding\.electron\SERVER\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:345:17)
    at Socket.<anonymous> (C:\modding\.electron\SERVER\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:105:22)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-release-server@1.5.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-release-server@1.5.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2020-11-25T20_19_03_070Z-debug.log
```
What is wrong ?

**Comment by abrorAbdullaev** [comment]
By all means, it really looks like an issue regarding the permissions.

Can be that you are running cmd or whatever CLI you use without admin permissions.
Can be that node.exe doesn't have the right to perform certain actions.

So, first of all. Please check what versions of NPM and NODE you are running.
Secondly try to run the app (ide, cli, cmd or what you use) as admin.
After all, check some google links about this issue, it doesn't seem to be connected to electron-release-server, but a general npm issue.

If cannot find a solution then also provide information about the environment (Operation System, NPM, NODE Version, App where you run command) so that others could try to reproduce the problem and try to find a solution.
