### ISSUE TITLE
NodsJS 14 incompatibility

### ISSUE THREAD

**Issue by beliaev-maksim** [ArekSredzki/electron-release-server#281]
on start you can get:
~~~
electron-release-server@1.5.2 start /home/electron/git/release_server
 node app.js

(node:9182) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
error: Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 20000)
    at Timeout.tooLong [as _onTimeout] (/home/electron/git/release_server/node_modules/sails/lib/app/private/loadHooks.js:85:21)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
~~~

Solution:
use nodejs v10

and hopefully somebody will fix it for v14

**Comment by Elaine87** [comment]
this works for me

**Comment by ArekSredzki** [comment]
The packages have now been updated and I've tested the server with NodeJS 19
https://github.com/ArekSredzki/electron-release-server/releases/tag/v2.1.0
