### ISSUE TITLE
Error on using Mongodb, outdated packages

### ISSUE THREAD

**Issue by gitcommitshow** [ArekSredzki/electron-release-server#297]
I tried using mongodb instead of Postgres and ran into some errors.
Changed `sails.config.model.connection` to `mongodb`. Installed `sails-mongo` latest version. On running the server, I got following error

```
error: Error: 
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
Cannot initialize Waterline.
The installed version of adapter `sails-mongo` is too new!
Please try installing a version < 1.0.
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

    at /release-server/node_modules/waterline/lib/waterline.js:90:15
    at /release-server/node_modules/waterline/node_modules/lodash/index.js:3073:15
    at baseForOwn (/release-server/node_modules/waterline/node_modules/lodash/index.js:2046:14)
    at /release-server/node_modules/waterline/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/release-server/node_modules/waterline/node_modules/lodash/index.js:3346:13)
    at module.exports.Waterline.initialize (/release-server/node_modules/waterline/lib/waterline.js:86:7)
    at buildWaterlineOntology (/release-server/node_modules/sails-hook-orm/lib/build-waterline-ontology.js:45:19)
    at Array.async.auto._buildOntology (/release-server/node_modules/sails-hook-orm/lib/initialize.js:388:7)
    at listener (/release-server/node_modules/sails-hook-orm/node_modules/async/lib/async.js:605:42)
    at /release-server/node_modules/sails-hook-orm/node_modules/async/lib/async.js:544:17
    at _arrayEach (/release-server/node_modules/sails-hook-orm/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/release-server/node_modules/sails-hook-orm/node_modules/async/lib/async.js:543:13)
    at processImmediate (internal/timers.js:461:21)
    at process.topLevelDomainCallback (domain.js:138:15)
    at process.callbackTrampoline (internal/async_hooks.js:124:14)
```

I don't think trying to install the version < 1.0 makes sense because the supported mongodb version for that would be <3.6 which mongodb has stopped supporting. The minimum required mongodb supported version must be 4.0. 
So that brings us to make the code work for latest sails mongo version (2.x or at least 1.x). This might require upgrading the sails version to v1.x as well.

**Comment by ArekSredzki** [comment]
Hi, I've pushed some major changes in addition to bringing in PRs that others had contributed. Please test with v2.1.0 and let me know how it goes :) 
https://github.com/ArekSredzki/electron-release-server/releases/tag/v2.1.0

**Comment by gitcommitshow** [comment]
Tried it with `"sails-mongo": "^2.1.0`, `sails@1.5.9` and mongodb server 6.0. 
Couldn't make it work. Initially the issue was that primary key was not identified as a valid mongo id. So I added `dontUseObjectIds: true` in each model. That solved the issue and server lifted up without any issues, was able to create/upload new assets. 

But then download didn't work.
On asset download, I get this error

```
error: Sending 500 ("Server Error") response: 
 TypeError: Cannot read properties of undefined (reading 'columnName')
/node_modules/waterline/lib/waterline/utils/query/forge-stage-three-query.js:591:49
    at arrayMap (/node_modules/@sailshq/lodash/lib/index.js:1587:25)
    at Function.map (/node_modules/@sailshq/lodash/lib/index.js:6918:14)
    at forgeStageThreeQuery (/node_modules/waterline/lib/waterline/utils/query/forge-stage-three-query.js:585:29)
    at helpFind (/node_modules/waterline/lib/waterline/utils/query/help-find.js:85:21)
    at _afterPotentiallyRunningBeforeLC (/node_modules/waterline/lib/waterline/methods/find.js:258:9)
    at _maybeRunBeforeLC (/node_modules/waterline/lib/waterline/methods/find.js:232:16)
    at Deferred._.extend._WLModel [as _handleExec] (/node_modules/waterline/lib/waterline/methods/find.js:234:9)
    at Deferred.exec (/node_modules/parley/lib/private/Deferred.js:286:10)
    at Deferred.tryCatcher (/node_modules/parley/node_modules/bluebird/js/release/util.js:11:23)
    at ret (eval at makeNodePromisifiedEval (/node_modules/parley/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at Deferred.toPromise (/node_modules/parley/lib/private/Deferred.js:572:19)
```

Apologies for getting back this late @ArekSredzki , I went on to explore other solutions but none worked out.

**Comment by gitcommitshow** [comment]
The issue is fixed, it works after following changes 

* add `columnName: '_id'` to all primaryKey attributes
* add `dontUseObjectIds: true` to all models
* Keep auto creation of created/updated fields
     ```
      models.attributes: {
          createdAt: { type: 'string', autoCreatedAt: true, },
          updatedAt: { type: 'string', autoUpdatedAt: true, },
      }
     ```
     I had removed those earlier because in a test project, they were being created automatically without this setting. But removing these lines caused the above error I mentioned.
