### ISSUE TITLE
Error while starting app

### ISSUE THREAD

**Issue by pierrbt** [ArekSredzki/electron-release-server#335]
I configured the app on my Linux server, and it has displayed an error so I tried it on my Windows PC but t does not work either. It displays the same error. For information, I use PostgreSQL, with v2land-sails-pg-session but it's strange.

`local.js` : 
```js
module.exports = {
  appUrl: 'https://ers.veagle.fr/',
  auth: {
    static: {
      username: 'admin',
      password: '*****'
    },
  },

  jwt: {
    token_secret: 'imrzjuQBtKlDTMKDprfmrvAy3iev82dUqr2aAYodn6SnpIlP4Yb3jANQm008iY9'
  },

  models: {
    datastore: 'postgresql',
    dataEncryptionKeys: {
      default: 'yOU3dU+TR9wt1m1jnfK/4pE+NXCB8b9TW23WNz+HidA='
    },
  },

datatores: {
        postgresql: {
            adapter: 'sails-postgresql',
            host: 'localhost',
            user: 'electron_release_server_user',
            password: '*********',
            database: 'electron_release_server'
        }
    },

    session: {
        secret: 'pVwcdPRBbyMz8Qkaw8dCT2Dw9cSLaEhdCjcxThpdaszbjPro50bghqETMwSgnJC',
        database: 'electron_release_server_sessions',
        host: 'localhost',
        user: 'electron_release_server_user',
        password: '***********',
        port: 5432
    },
  files: {
    dirname: 'PATH_FOR_ASSETS',
  }

};
```

`session.js` : 
```js

module.exports.session = {

postgresql: {
adapter: 'v2land-sails-pg-session',
host: 'localhost',
user: 'electron_release_server_user',
password: '************',
database: 'electron_release_server'
}
};
```

Here's the error : 
```ps
PS C:\Users\pierr\Documents\electron-release-server> npm start

> electron-release-server@2.1.3 start
> node app.js

 info: ·• Auto-migrating...  (alter)
 info:    Hold tight, this could take a moment.
error: A hook (`orm`) failed to load!
error: Could not tear down the ORM hook.  Error details: Error: Invalid data store identity. No data store exist with that identity.
    at Object.teardown (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\helpers\teardown.js:60:26)
    at wrapper (C:\Users\pierr\Documents\electron-release-server\node_modules\@sailshq\lodash\lib\index.js:3282:19)
    at parley.retry [as _handleExec] (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\node_modules\machine\lib\private\help-build-machine.js:1076:19)
    at Deferred.exec (C:\Users\pierr\Documents\electron-release-server\node_modules\parley\lib\private\Deferred.js:286:10)
    at Deferred.switch (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\node_modules\machine\lib\private\help-build-machine.js:1469:16)
    at teardownDatastore (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\lib\adapter.js:97:18)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\node_modules\async\dist\async.js:3113:16
    at replenish (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\node_modules\async\dist\async.js:1014:17)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\node_modules\async\dist\async.js:1019:9
    at eachLimit$1 (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\node_modules\async\dist\async.js:3199:24)
    at Object.<anonymous> (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\node_modules\async\dist\async.js:1049:16)
    at Object.teardown (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\lib\adapter.js:92:13)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\lib\waterline.js:767:27
    at C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\node_modules\async\dist\async.js:3113:16
    at eachOfArrayLike (C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\node_modules\async\dist\async.js:1072:9)
    at eachOf (C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\node_modules\async\dist\async.js:1120:5)
    at Object.eachLimit (C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\node_modules\async\dist\async.js:3175:5)
    at Object.teardown (C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\lib\waterline.js:751:11)
    at Hook.teardown (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\index.js:246:30)
    at Sails.wrapper (C:\Users\pierr\Documents\electron-release-server\node_modules\@sailshq\lodash\lib\index.js:3282:19)
    at Object.onceWrapper (node:events:627:28)
    at Sails.emit (node:events:513:28)
error: Failed to lift app: Exception: `registerDataStore` failed ("badConfiguration").  The configuration was invalid.  (Also got an additional error -- see `.raw`).
    at Object.registerDatastore (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\lib\adapter.js:57:17)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\lib\waterline.js:717:27
    at C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\node_modules\async\dist\async.js:3113:16
    at eachOfArrayLike (C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\node_modules\async\dist\async.js:1072:9)
    at eachOf (C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\node_modules\async\dist\async.js:1120:5)
    at Object.eachLimit (C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\node_modules\async\dist\async.js:3175:5)
    at Object.initialize (C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\lib\waterline.js:653:11)
    at buildOntologyAndRunAutoMigrations (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\lib\build-ontology-and-run-auto-migrations.js:55:7)
    at async.auto._buildOntology (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\lib\initialize.js:456:7)
    at runTask (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1635:13)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1575:13
    at processQueue (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1585:13)
    at taskComplete (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1604:9)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1628:17
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:972:16
    at async.auto._checkAdapterCompatibility (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\lib\initialize.js:428:14)
    at runTask (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1635:13)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1575:13
    at processQueue (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1585:13)
    at taskComplete (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1604:9)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1628:17
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:972:16
error: More details (raw): Error: Datastore  `postgresql` config is missing a host value.
    at Object.registerDataStore (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\helpers\register-data-store.js:98:63)
    at wrapper (C:\Users\pierr\Documents\electron-release-server\node_modules\@sailshq\lodash\lib\index.js:3282:19)
    at parley.retry [as _handleExec] (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\node_modules\machine\lib\private\help-build-machine.js:1076:19)
    at Deferred.exec (C:\Users\pierr\Documents\electron-release-server\node_modules\parley\lib\private\Deferred.js:286:10)
    at Deferred.now (C:\Users\pierr\Documents\electron-release-server\node_modules\parley\lib\private\Deferred.js:592:8)
    at Deferred.now (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\node_modules\machine\lib\private\help-build-machine.js:1317:51)
    at Deferred.execSync (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\node_modules\machine\lib\private\help-build-machine.js:1530:23)
    at Object.registerDatastore (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-postgresql\lib\adapter.js:63:12)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\lib\waterline.js:717:27
    at C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\node_modules\async\dist\async.js:3113:16
    at eachOfArrayLike (C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\node_modules\async\dist\async.js:1072:9)
    at eachOf (C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\node_modules\async\dist\async.js:1120:5)
    at Object.eachLimit (C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\node_modules\async\dist\async.js:3175:5)
    at Object.initialize (C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\lib\waterline.js:653:11)
    at buildOntologyAndRunAutoMigrations (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\lib\build-ontology-and-run-auto-migrations.js:55:7)
    at async.auto._buildOntology (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\lib\initialize.js:456:7)
    at runTask (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1635:13)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1575:13
    at processQueue (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1585:13)
    at taskComplete (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1604:9)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:1628:17
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-hook-orm\node_modules\async\dist\async.js:972:16
C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\lib\waterline\utils\system\validate-datastore-connectivity.js:22
  if (!_.has(adapterDSEntry.driver, 'getConnection') || !_.has(adapterDSEntry.driver, 'releaseConnection')) {
                            ^

TypeError: Cannot read properties of undefined (reading 'driver')
    at validateDatastoreConnectivity (C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\lib\waterline\utils\system\validate-datastore-connectivity.js:22:29)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\waterline\lib\waterline.js:722:18
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-disk\node_modules\async\dist\async.js:473:16
    at eachOfArrayLike (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-disk\node_modules\async\dist\async.js:1060:9)
    at eachOf (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-disk\node_modules\async\dist\async.js:1120:5)
    at Object.eachLimit (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-disk\node_modules\async\dist\async.js:3175:5)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-disk\index.js:120:15
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-disk\index.js:112:18
    at proceedToFinalAfterExecLC (C:\Users\pierr\Documents\electron-release-server\node_modules\parley\lib\private\Deferred.js:1157:14)
    at proceedToInterceptsAndChecks (C:\Users\pierr\Documents\electron-release-server\node_modules\parley\lib\private\Deferred.js:913:12)
    at proceedToAfterExecSpinlocks (C:\Users\pierr\Documents\electron-release-server\node_modules\parley\lib\private\Deferred.js:845:10)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\parley\lib\private\Deferred.js:303:7
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-disk\node_modules\machine\lib\private\help-build-machine.js:953:53
    at handlerCbs.success (C:\Users\pierr\Documents\electron-release-server\node_modules\sails-disk\node_modules\machine\lib\private\help-build-machine.js:814:26)
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-disk\node_modules\machinepack-fs\machines\ensure-dir.js:50:20
    at C:\Users\pierr\Documents\electron-release-server\node_modules\sails-disk\node_modules\fs-extra\lib\mkdirs\mkdirs.js:54:16
    at callback (C:\Users\pierr\Documents\electron-release-server\node_modules\graceful-fs\polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:208:5)
```

**Comment by busterbogheart** [comment]
You've spelled `datastores` incorrectly
