### ISSUE TITLE
npm start - error: A hook(`orm`) failed to load!

### ISSUE THREAD

**Issue by black-snow** [ArekSredzki/electron-release-server#39]
`npm start` leaves me with this:

> error: A hook (`orm`) failed to load!
error: TypeError: Cannot read property 'config' of undefined
    at validateModelDef (/Users/xxx/electron-release-server/node_modules/sails-hook-orm/lib/validate-model-def.js:108:84)
    at /Users/xxx/electron-release-server/node_modules/sails-hook-orm/lib/initialize.js:218:36
    at arrayEach (/Users/xxx/electron-release-server/node_modules/sails-hook-orm/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/xxx/electron-release-server/node_modules/sails-hook-orm/node_modules/lodash/index.js:3345:13)
    at Array.async.auto._normalizeModelDefs (/Users/xxx/electron-release-server/node_modules/sails-hook-orm/lib/initialize.js:216:11)
    at listener (/Users/xxx/electron-release-server/node_modules/async/lib/async.js:605:42)
    at /Users/xxx/electron-release-server/node_modules/async/lib/async.js:544:17
    at _arrayEach (/Users/xxx/electron-release-server/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/Users/xxx/electron-release-server/node_modules/async/lib/async.js:543:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17) [TypeError: Cannot read property 'config' of undefined]

Any thoughts? :(

**Comment by ArekSredzki** [comment]
Please read the deploy instructions. You will get this error if you haven't copied local.template to local.js

**Comment by black-snow** [comment]
I'd be glad if it was that easy. I do have a `local.js`. 
`cp config/local.template config/local.js`

**Comment by nandwabee** [comment]
@black-snow Are you using MongoDB by any chance?

**Comment by GusCaplan** [comment]
i have the same issue, and i have local.js

**Comment by black-snow** [comment]
@nandwabee No, I don't. But I actually dropped `electron-release-server` so I can't tell you any more.

**Comment by GusCaplan** [comment]
same

**Comment by yahyaKacem** [comment]
still having this error with node v5.12.0 & v5.11.1:
```
> electron-release-server@1.4.3 start /var/www/tests/electron-release-server
> node app.js

error: A hook (`controllers`) failed to load!
error: `include-all` attempted to `require(/var/www/tests/electron-release-server/api/controllers/VersionController.js)`, but an error occurred:: 
Details:SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /var/www/tests/electron-release-server/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:271:33
    at Array.forEach (native)
    at _recursivelyIncludeAll (/var/www/tests/electron-release-server/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:174:11)
    at includeAll (/var/www/tests/electron-release-server/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:292:5)
    at helpBuildDictionary (/var/www/tests/electron-release-server/node_modules/sails/node_modules/include-all/lib/help-build-dictionary.js:43:15)
    at Function.module.exports.optional (/var/www/tests/electron-release-server/node_modules/sails/node_modules/include-all/index.js:67:10)
    at Hook.loadControllers (/var/www/tests/electron-release-server/node_modules/sails/lib/hooks/moduleloader/index.js:324:18)
    at Hook.wrapper [as loadControllers] (/var/www/tests/electron-release-server/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at Hook.loadAndRegisterControllers (/var/www/tests/electron-release-server/node_modules/sails/lib/hooks/controllers/to-load-and-register-controllers.js:33:19)
    at Hook.initialize (/var/www/tests/electron-release-server/node_modules/sails/lib/hooks/controllers/index.js:59:12)
    at Hook.wrapper [as initialize] (/var/www/tests/electron-release-server/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at /var/www/tests/electron-release-server/node_modules/sails/lib/hooks/index.js:88:16
    at /var/www/tests/electron-release-server/node_modules/sails/node_modules/async/lib/async.js:52:16
    at /var/www/tests/electron-release-server/node_modules/sails/node_modules/async/lib/async.js:548:17
    at /var/www/tests/electron-release-server/node_modules/sails/node_modules/async/lib/async.js:542:17
error: A hook (`orm`) failed to load!
```
switching to node v7.4.0 I get this error:
```
Error creating a connection to Postgresql using the following settings:
 { host: 'localhost',
  port: 5432,
  schema: true,
  ssl: false,
  adapter: 'sails-postgresql',
  identity: 'postgresql',
  password: '[redacted]' }

* * *
Complete error details:
 { error: password authentication failed for user "yahya"
    at Connection.parseE (/var/www/tests/electron-release-server2/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/www/tests/electron-release-server2/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/var/www/tests/electron-release-server2/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'error',
  length: 94,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '288',
  routine: 'auth_failed' }


Troubleshooting tips:

 -> You appear to be trying to use a Postgresql install on localhost. Maybe the database server isn't running, or is not installed?

 -> Is your Postgresql configuration correct?  Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, yo
u should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10. To override default settings, 
specify the desired properties on the relevant Postgresql "connection" config object where the host/port/database/etc. are configured. If you're using Sails, this is generally 
located in `config/connections.js`, or wherever your environment-specific database configuration is set.

 -> Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize`
 set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10.


error: A hook (`orm`) failed to load!

Error creating a connection to Postgresql using the following settings:
 { host: 'localhost',
  port: 5432,
  schema: true,
  ssl: false,
  adapter: 'sails-postgresql',
  identity: 'postgresql',
  password: '[redacted]' }

* * *
Complete error details:
 { error: password authentication failed for user "yahya"
    at Connection.parseE (/var/www/tests/electron-release-server2/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/www/tests/electron-release-server2/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/var/www/tests/electron-release-server2/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'error',                                                                                                                                                       
  length: 94,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '288',
  routine: 'auth_failed' }


Troubleshooting tips:

 -> You appear to be trying to use a Postgresql install on localhost. Maybe the database server isn't running, or is not installed?

 -> Is your Postgresql configuration correct?  Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, yo
u should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10. To override default settings, 
specify the desired properties on the relevant Postgresql "connection" config object where the host/port/database/etc. are configured. If you're using Sails, this is generally 
located in `config/connections.js`, or wherever your environment-specific database configuration is set.

 -> Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize`
 set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10.



Error creating a connection to Postgresql using the following settings:
 { host: 'localhost',
  port: 5432,
  schema: true,
  ssl: false,
  adapter: 'sails-postgresql',
  identity: 'postgresql',
  password: '[redacted]' }

* * *
Complete error details:
 { error: password authentication failed for user "yahya"
    at Connection.parseE (/var/www/tests/electron-release-server2/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
 at Connection.parseMessage (/var/www/tests/electron-release-server2/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/var/www/tests/electron-release-server2/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'error',
  length: 94,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '288',
  routine: 'auth_failed' }


Troubleshooting tips:

 -> You appear to be trying to use a Postgresql install on localhost. Maybe the database server isn't running, or is not installed?

 -> Is your Postgresql configuration correct?  Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10. To override default settings, specify the desired properties on the relevant Postgresql "connection" config object where the host/port/database/etc. are configured. If you're using Sails, this is generally located in `config/connections.js`, or wherever your environment-specific database configuration is set.

 -> Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10.


error: error: password authentication failed for user "yahya"
    at Connection.parseE (/var/www/tests/electron-release-server2/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/www/tests/electron-release-server2/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/var/www/tests/electron-release-server2/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```
I followed the instruction in the [deploy](https://github.com/ArekSredzki/electron-release-server/blob/master/docs/deploy.md) and the [database setup](https://github.com/ArekSredzki/electron-release-server/blob/master/docs/database.md).
what I'm I doing wrong?

**Comment by ArekSredzki** [comment]
@yahyaKacem
Only Node LTS is offically supported , but 7.x should work too. Sounds like your Postgres credentials are wrong

**Comment by yahyaKacem** [comment]
@ArekSredzki the credentials are correct I am able to connect to postgresql fro the browser `localhost/phppgadmin/` username and password are correct, I just deleted everything and reinstalled again but still having the same error:
```
$ npm start 

> electron-release-server@1.4.3 start /var/www/Work/electron-release-server
> node app.js


error: Server failed to start.
error: (received error: EACCES)
error: 
error: Troubleshooting tips:
error: 
error:  -> Do you have a slow Grunt task, or lots of assets?
error: 
error:  -> Do you have permission to use port 80 on this system? (you might try `sudo`)
error: 
error:  -> Is something else already running on port 80 ?
error: 
error:  -> Are you deploying on a platform that requires an explicit hostname, like OpenShift?
error:     (Try setting the `explicitHost` config to the hostname where the server will be accessible.)
error:     (e.g. `mydomain.com` or `183.24.244.42`)


npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/home/yahya/.nvm/versions/node/v7.4.0/bin/node" "/home/yahya/.nvm/versions/node/v7.4.0/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! electron-release-server@1.4.3 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-release-server@1.4.3 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-release-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-release-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-release-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/Work/electron-release-server/npm-debug.log
```
I even added the `explicitHost` but still the same error.
I'm on ubuntu 16.04 and psql (PostgreSQL) 9.5.5.

**Comment by ArekSredzki** [comment]
What does your config file look like?
While I do think this is a configuration issue, have you tried using node 6.x?

**Comment by yahyaKacem** [comment]
config file:
```
module.exports = {
  appUrl: 'localhost',
  auth: {
    static: {
      username: 'yahya',
      password: 'azerty'
    },
  },
  jwt: {
    token_secret: 'aa1LcFs3O48fly92Jej6wOiQR1s2S3LDRuGXce5PvoSMRRABoEyIr7dTJ8Ur06y'
  },
  connections: {
    postgresql: {
      adapter: 'sails-postgresql',
      host: 'localhost',
      explicitHost: 'localhost',
      user: 'yahya',
      password: 'azerty',
      poolSize: 5,
      database: 'electron_release_server'
    }
  },
  session: {
    secret: 'aa1LcFs3O48fly92Jej6wOiQR1s2S3LDRuGXce5PvoSMRRABoEyIr7dTJ8Ur06y',
    database: 'electron_release_server_session',
    host: 'localhost',
    user: 'yahya',
    password: 'azerty',
    port: 5432
  },
  files: {
    dirname: 'assets'
  }
};
```
yes, I tried node v6.9.4 no success too.

**Comment by gokatz** [comment]
@yahyaKacem, can you try using `sudo`, `sudo npm start`? It works for me...

**Comment by pmendhiratta** [comment]
I am facing the same issue although i have all the credentials right, how is the issue fixed?
Error creating a connection to Postgresql using the following settings:
 { host: 'localhost',
  port: 5432,
  schema: true,
  ssl: false,
  adapter: 'sails-postgresql',
  user: 'electron_release_server_user',
  password: 'MySecure',
  database: 'traverse_updater',
  identity: 'postgresql' }

* * *
Complete error details:
 { error: password authentication failed for user "electron_release_server_user"
    at Connection.parseE (C:\Work\Repo\tims-electron-release-server\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (C:\Work\Repo\tims-electron-release-server\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (C:\Work\Repo\tims-electron-release-server\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
  name: 'error',
  length: 135,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'src\\backend\\libpq\\auth.c',
  line: '305',
  routine: 'auth_failed' }

**Comment by gliss** [comment]
I having this issue too. Everything is ok if I use the the MemoryStore for sessions but as soon as I enable sails-pg-session it fails with the following error:
```
error: sails-pg-session#PostSQLStore -  error: password authentication failed for user "electron_release_server_user"
    at Connection.parseE (E:\admin\Documents\Repos\electron-release-server\node_modules\sails-pg-session\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\admin\Documents\Repos\electron-release-server\node_modules\sails-pg-session\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\admin\Documents\Repos\electron-release-server\node_modules\sails-pg-session\node_modules\pg\lib\connection.js:105:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
Someone then suggested that sails-pg-session dependency 'pg' needed to be updated to 6.4.0 which I did but now i get the below error;

```
error: A hook (`session`) failed to load!
error: Could not load Connect session adapter :: sails-pg-session

TypeError: Cannot read property 'Store' of undefined
    at module.exports (E:\admin\Documents\Repos\electron-release-server\node_modules\sails-pg-session\lib\sails-pg-session.js:24:31)
    at Hook.initialize (E:\admin\Documents\Repos\electron-release-server\node_modules\sails\lib\hooks\session\index.js:222:35)
    at Hook.wrapper [as initialize] (E:\admin\Documents\Repos\electron-release-server\node_modules\@sailshq\lodash\lib\index.js:3275:19)
    at E:\admin\Documents\Repos\electron-release-server\node_modules\sails\lib\hooks\index.js:88:16
    at E:\admin\Documents\Repos\electron-release-server\node_modules\sails\node_modules\async\lib\async.js:52:16
    at E:\admin\Documents\Repos\electron-release-server\node_modules\sails\node_modules\async\lib\async.js:548:17
    at E:\admin\Documents\Repos\electron-release-server\node_modules\sails\node_modules\async\lib\async.js:542:17
    at _arrayEach (E:\admin\Documents\Repos\electron-release-server\node_modules\sails\node_modules\async\lib\async.js:85:13)
    at Immediate.taskComplete [as _onImmediate] (E:\admin\Documents\Repos\electron-release-server\node_modules\sails\node_modules\async\lib\async.js:541:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)


error: A hook (`orm`) failed to load!
```

**Comment by wslp12** [comment]
same issue too 
yunjiman $ sudo npm start
Password:

> electron-release-server@1.5.2 start /Users/yunjiman/Documents/workspace/dz_p_test/TEST/electron-release-server
> node app.js

error: A hook (`orm`) failed to load!
error: error: column r.consrc does not exist
    at Connection.parseE (/Users/yunjiman/Documents/workspace/dz_p_test/TEST/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/yunjiman/Documents/workspace/dz_p_test/TEST/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/yunjiman/Documents/workspace/dz_p_test/TEST/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

any one help me ?

**Comment by gliss** [comment]
@wslp12 change your package.json to use v2land-sails-pg-session rather than sails-pg-session

**Comment by wslp12** [comment]
@gliss thanks, it work :)

**Comment by beliaev-maksim** [comment]
@gliss , @wslp12 
can you please help me how you changed package.json?
should I revert also "require" in .js files or is there some trick?

otherwise I am getting:
Do you have the Connect session adapter installed in this project?

**Comment by black-snow** [comment]
What do you mean by "revert require"?

**Comment by beliaev-maksim** [comment]
I mean where does it used and what does it influence ?

I ran 
npm i v2land-sails-pg-session
npm uninstall sails-pg-session

and get now:
error: A hook (`session`) failed to load!
error: Could not load Connect session adapter :: sails-pg-session

however here in instruction it is still the same adapter in config/session.js:
https://www.npmjs.com/package/v2land-sails-pg-session

**Comment by beliaev-maksim** [comment]
ok, found by myself
run:
npm i v2land-sails-pg-session
npm uninstall sails-pg-session

and modify session.js
module.exports.session = {
  adapter: 'v2land-sails-pg-session',
  database: 'electron_release_server',
    host: 'localhost',
    user: 'electron_release_server_user',
    password: '*****',
    port: 5432
};
