### ISSUE TITLE
Failed: Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by bapatel1** [ArekSredzki/electron-release-server#40]
@ArekSredzki , First of all, great tool and code. I really like your work. I am setting your server tool on our production server but it's giving me this error - 
```
"WebSocket connection to 'wss://electronreleaseserver.xyz.abc.edu/socket.io/?__sails_io_sdk_version=0…tform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
sails.io.js:438  
        Socket is trying to reconnect to Sails...
_-|>_-  (attempt #5)
```

If i run same code on production server using npm start, works fine on localhost:1337

Also, I have following in local.js under config - 

```
 connections: {
    postgresql: {
      adapter: 'sails-disk'
    }
  },
```

Please help if you have any idea about this error, I have release this week.

**Comment by ArekSredzki** [comment]
Thanks for the feedback! It means a lot 😊

The connections section of your config actually refers to database connectors. For production you should use waterline's postgresql adapter (see the docs).

Your error however is an issue with websockets. It's likely that whatever web server you're using (nginx or apache) is not redirecting the websockets to the sails process. The deployment docs describe how to do this for nginx

**Comment by bapatel1** [comment]
@ArekSredzki I am using IISNode to deploy this website on IIS and I still want to use disk or local file system , which i am using in development mode. So in summary, everything same as development mode for production. I understand the security risk against sails-disk vs. postgresql/mongo but we need to finish this for demo we have this week. 

Here is my entire local.js
```

module.exports = {

  appUrl: 'http://localhost:1338',

  auth: {
    static: {
      username: 'USERNAME',
      password: 'PASSWORD'
    },
  },

  jwt: {
    token_secret: 'I HAVE TOKEN HERE'
  },

  connections: {
    postgresql: {
      adapter: 'sails-disk'
    }
  },
  files: {
    dirname: 'D:\\project\\electron-release-server\\releases',
  },

   port: process.env.PORT || 1338

   //environment: process.env.NODE_ENV || 'development'

};

```

**Comment by ArekSredzki** [comment]
@bapatel1 You most certainly should *not* be using development mode for production... ever.
It will take you at most 30 mins (likely less) to get a postgresql instance running. `sails-disk` will not scale whatsoever. It will a) crash and burn if you try to spin up multiple node instances (you're using `iisnode` for that reason presumably) b) is entirely blocking it does not handle concurrent requests.

It's not just a security risk, it's just asking for a headache.

**Comment by ArekSredzki** [comment]
As for the websocket issue, that's caused by the fact that you're using an http server, `iisnode` in your case. You'll have to configure re-write rules for the websocket connection. This might be a good place to start: https://tomasz.janczuk.org/2013/01/hosting-socketio-websocket-apps-in-iis.html

If you really are just setting this up for a demo though, why are you using iisnode at all?

Personally I don't see why anyone would deploy node web services on windows... but that's your call.

**Comment by bapatel1** [comment]
@ArekSredzki Thank you, i think i see your point for using and setup postgres and i tried last night for doing those settings based on the documentation. I am getting this error now  (I don't know anything about sails or postgres so hard to get some resolution)

```


error: A hook (`orm`) failed to load!
error: error: password authentication failed for user "electron_release_server_user"
    at Connection.parseE (D:\Project\electron-release-server\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (D:\Project\electron-release-server\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (D:\Project\electron-release-server\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20) { error: password authentication failed for user "electron_release_server_user"
    at Connection.parseE (D:\Project\electron-release-server\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (D:\Project\electron-release-server\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (D:\Project\electron-release-server\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
  name: 'error',
  length: 117,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '304',
  routine: 'auth_failed' }

Error creating a connection to Postgresql using the following settings:
 { host: 'localhost',
  port: 5432,
  schema: true,
  ssl: false,
  adapter: 'sails-postgresql',
  user: 'electron_release_server_user',
  password: '[redacted]',
  database: 'electron_release_server',
  identity: 'postgresql' }

* * *
Complete error details:
 { Error: read ECONNRESET
    at exports._errnoException (util.js:953:11)
    at TCP.onread (net.js:563:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }


Troubleshooting tips:

 -> You appear to be trying to use a Postgresql install on localhost. Maybe the database server isn't running, or is not installed?

 -> Is your Postgresql configuration correct?  Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10. To override default settings, specify the desired properties on the relevant Postgresql "connection" config object where the host/port/database/etc. are configured. If you're using Sails, this is generally located in `config/connections.js`, or wherever your environment-specific database configuration is set.

 -> Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10.
```

**Comment by bapatel1** [comment]
I think replacing Node 6.x with 5.1.x fixed above issue. I am running now in production mode with postgres Db. I am still getting those websockets related errors - 

```
"WebSocket connection to 'wss://electronreleaseserver.xyz.abc.edu/socket.io/?__sails_io_sdk_version=0…tform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
sails.io.js:438  
        Socket is trying to reconnect to Sails...
_-|>_-  (attempt #5)
```

**Comment by bapatel1** [comment]
@ArekSredzki - updating latest IISNode 2.21.x fixed above web sockets issues as well. Now my API is not working 

```
angular.js:11821 POST https://electronreleaseserver.abc.edu/api/asset 404 (Not Found)
```
