### ISSUE TITLE
"https" is not working.

### ISSUE THREAD

**Issue by bommuraj2012** [ArekSredzki/electron-release-server#43]
Thanks for this awesome electron release server.
It's working very fine with port 80 (http),
When i enable https , it was throwing below error.
NOTE: i purchased cert from godaddy and placed them in config/ssl directory.
Also enabled port 443 in env/production.js

> electron-release-server@1.1.1 start /usr/local/electron-release-server
> node app.js

/usr/local/electron-release-server/config/local.js:99
   ssl: {
   ^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/local/electron-release-server/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/usr/local/electron-release-server/node_modules/include-all/index.js:44:9)
    at buildDictionary (/usr/local/electron-release-server/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.aggregate (/usr/local/electron-release-server/node_modules/sails/node_modules/sails-build-dictionary/index.js:190:9)
    at Array.loadOtherConfigFiles (/usr/local/electron-release-server/node_modules/sails/lib/hooks/moduleloader/index.js:239:27)
    at /usr/local/electron-release-server/node_modules/sails/node_modules/async/lib/async.js:591:38
    at _arrayEach (/usr/local/electron-release-server/node_modules/sails/node_modules/async/lib/async.js:85:13)
    at Object.async.auto (/usr/local/electron-release-server/node_modules/sails/node_modules/async/lib/async.js:552:9)

Thanks,
Raj

**Comment by ArekSredzki** [comment]
Hi Raj,

Glad that you're enjoying the server!
Please ensure that there's a comma on the line (that actually has something on it) before the one dealing with ssl :)

**Comment by bommuraj2012** [comment]
Oh yes, Thank you.
Got it.

Thanks,
Raj
