### ISSUE TITLE
On "checking-for-update" in Windows 64 I get The remote server returned an error: (500) Internal Server Error

### ISSUE THREAD

**Issue by rohit-lakhanpal** [ArekSredzki/electron-release-server#51]
Im trying to use auto-updates with electron-boilerplate & electron-builder. To host my updates I've setup a test electron-release-server & set my feed url to http://52.64.55.12:1337/update/win64/0.1.0/stable.

Trying desperately to get auto-updates on windows working but my solution does not seem to work. 

Can someone help me & check if my release server has been setup correctly? Also, if anyone could share sample code for auto-update on windows it would be much appreciated. 

My squirrel log is as follows ..
`2016-07-17 20:15:42> Program: Starting Squirrel Updater: --download http://52.64.55.12:1337/update/win64/0.1.0/stable
2016-07-17 20:15:43> Program: Fetching update information, downloading from http://52.64.55.12:1337/update/win64/0.1.0/stable
2016-07-17 20:15:43> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\rousr\AppData\Local\Temp\.squirrel-lock-295D93693F94C0D6D2061F2C88BED0805730F7ED: System.IO.IOException: The process cannot access the file 'C:\Users\rousr\AppData\Local\Temp\.squirrel-lock-295D93693F94C0D6D2061F2C88BED0805730F7ED' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2016-07-17 20:15:43> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\rousr\AppData\Local\Temp\.squirrel-lock-295D93693F94C0D6D2061F2C88BED0805730F7ED: System.IO.IOException: The process cannot access the file 'C:\Users\rousr\AppData\Local\Temp\.squirrel-lock-295D93693F94C0D6D2061F2C88BED0805730F7ED' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2016-07-17 20:15:43> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\rousr\AppData\Local\Temp\.squirrel-lock-295D93693F94C0D6D2061F2C88BED0805730F7ED: System.IO.IOException: The process cannot access the file 'C:\Users\rousr\AppData\Local\Temp\.squirrel-lock-295D93693F94C0D6D2061F2C88BED0805730F7ED' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2016-07-17 20:15:43> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\rousr\AppData\Local\Temp\.squirrel-lock-295D93693F94C0D6D2061F2C88BED0805730F7ED: System.IO.IOException: The process cannot access the file 'C:\Users\rousr\AppData\Local\Temp\.squirrel-lock-295D93693F94C0D6D2061F2C88BED0805730F7ED' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2016-07-17 20:15:44> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\rousr\AppData\Local\Temp\.squirrel-lock-295D93693F94C0D6D2061F2C88BED0805730F7ED: System.IO.IOException: The process cannot access the file 'C:\Users\rousr\AppData\Local\Temp\.squirrel-lock-295D93693F94C0D6D2061F2C88BED0805730F7ED' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2016-07-17 20:15:44> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\rousr\AppData\Local\Temp\.squirrel-lock-295D93693F94C0D6D2061F2C88BED0805730F7ED: System.IO.IOException: The process cannot access the file 'C:\Users\rousr\AppData\Local\Temp\.squirrel-lock-295D93693F94C0D6D2061F2C88BED0805730F7ED' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2016-07-17 20:15:44> CheckForUpdateImpl: Generated new staging user ID: badd65b5-e4bb-5d04-8f21-f24a3cad9bc3
2016-07-17 20:15:44> CheckForUpdateImpl: Downloading RELEASES file from http://52.64.55.12:1337/update/win64/0.1.0/stable
2016-07-17 20:15:44> FileDownloader: Downloading url: http://52.64.55.12:1337/update/win64/0.1.0/stable/RELEASES?id=electronboilerplate&localVersion=0.1.0&arch=amd64
2016-07-17 20:15:44> IEnableLogger: Failed to download url: http://52.64.55.12:1337/update/win64/0.1.0/stable/RELEASES?id=electronboilerplate&localVersion=0.1.0&arch=amd64: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-07-17 20:15:44> FileDownloader: Downloading url: http://52.64.55.12:1337/update/win64/0.1.0/stable/releases?id=electronboilerplate&localversion=0.1.0&arch=amd64
2016-07-17 20:15:44> IEnableLogger: Failed to download url: http://52.64.55.12:1337/update/win64/0.1.0/stable/releases?id=electronboilerplate&localversion=0.1.0&arch=amd64: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-07-17 20:15:44> CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-07-17 20:15:44> FileDownloader: Downloading url: http://52.64.55.12:1337/update/win64/0.1.0/stable/RELEASES?id=electronboilerplate&localVersion=0.1.0&arch=amd64
2016-07-17 20:15:45> IEnableLogger: Failed to download url: http://52.64.55.12:1337/update/win64/0.1.0/stable/RELEASES?id=electronboilerplate&localVersion=0.1.0&arch=amd64: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-07-17 20:15:45> FileDownloader: Downloading url: http://52.64.55.12:1337/update/win64/0.1.0/stable/releases?id=electronboilerplate&localversion=0.1.0&arch=amd64
2016-07-17 20:15:45> IEnableLogger: Failed to download url: http://52.64.55.12:1337/update/win64/0.1.0/stable/releases?id=electronboilerplate&localversion=0.1.0&arch=amd64: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)`

**Comment by ArekSredzki** [comment]
The server is returning a 500 code, what does the server log show?

Does version 0.1.0 exist on the server?

**Comment by ArekSredzki** [comment]
@rohit-lakhanpal ping

**Comment by savenko** [comment]
Hello!
I have also this error. I upload files, but get error 404

**Comment by ArekSredzki** [comment]
Hi! The platform must be "windows_64"

**Comment by savenko** [comment]
I am chage platform but can not download file https://yadi.sk/i/b7X0-VtItezy6

**Comment by sinfere** [comment]
this repo is so bad, a waste of time, I'm so angry....

I just used Charles to check the real request, I found:
GET /update/win64/1.0.0/stable/releases?id=app&localversion=1.0.0&arch=amd64 HTTP/1.1

can this be called compatible ?

I hate this repo.

**Comment by tarjei** [comment]
Just noting for someone coming here after searching for the 500 return code. Here's a few tips that can help:

* You need to upload both -nupkg and .exe files for each release (for windows)
* If you are using a channel that is not the stable channel, remember to add the channel to the update url.
