### ISSUE TITLE
Unable to add Version

### ISSUE THREAD

**Issue by MTRNord** [ArekSredzki/electron-release-server#67]
I run my Version on Heroku and my postgresql on ElephantSQL.

When I try to add a new Version I get:

```
2016-09-07T20:23:26.747987+00:00 heroku[router]: at=info method=POST path="/api/version" host=ls-update-alt.herokuapp.com request_id=ab4ef905-9483-4ee3-8036-547f65b9a8a4 fwd="91.35.4.246" dyno=web.1 connect=0ms service=49ms status=500 bytes=356
2016-09-07T20:23:26.741094+00:00 app[web.1]: Sending 500 ("Server Error") response: 
2016-09-07T20:23:26.741113+00:00 app[web.1]:  Error (E_UNKNOWN) :: Encountered an unexpected error
2016-09-07T20:23:26.741113+00:00 app[web.1]: error: relation "public.channel" does not exist
2016-09-07T20:23:26.741115+00:00 app[web.1]:     at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
2016-09-07T20:23:26.741116+00:00 app[web.1]:     at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
2016-09-07T20:23:26.741116+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
2016-09-07T20:23:26.741117+00:00 app[web.1]:     at emitOne (events.js:90:13)
2016-09-07T20:23:26.741119+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:153:18)
2016-09-07T20:23:26.741119+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:111:10)
2016-09-07T20:23:26.741120+00:00 app[web.1]:     at TCP.onread (net.js:534:20)
2016-09-07T20:23:26.741121+00:00 app[web.1]: 
```

**Comment by ArekSredzki** [comment]
You must initially run the server in development mode in order to initialize the database.
I presume that the tables haven't been created.

**Comment by MTRNord** [comment]
After setting NODE_ENV to develop it worked because normaly Heroku has it on production

**Comment by ArekSredzki** [comment]
Excellent. Make sure to set NODE_ENV back to `production` after the first run!

**Comment by eriklarko** [comment]
For real? The database setup for this project really needs a looking over...
