### ISSUE TITLE
Permission denied for relation asset

### ISSUE THREAD

**Issue by makeitcount** [ArekSredzki/electron-release-server#76]
Getting this error on npm start
```
error: A hook (`orm`) failed to load!
error: Error (E_UNKNOWN) :: Encountered an unexpected error
error: permission denied for relation asset
    at Connection.parseE (/home/pradeep/Projects/utilities/desktop/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/pradeep/Projects/utilities/desktop/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/pradeep/Projects/utilities/desktop/electron-release-server/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)

Details:  error: permission denied for relation asset
```

**Comment by ArekSredzki** [comment]
Hi @makeitcount You must first run the server in debug mode in order to initialize the database tables. After that be sure to always run it in production mode
